//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

//
// This source code was auto-generated by xsd, Version=4.8.3928.0.
//


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.worldbank.org")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.worldbank.org", IsNullable=false)]
public partial class countries {

    private countriesCountry[] countryField;

    private string pageField;

    private string pagesField;

    private string per_pageField;

    private string totalField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("country")]
    public countriesCountry[] country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string page {
        get {
            return this.pageField;
        }
        set {
            this.pageField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pages {
        get {
            return this.pagesField;
        }
        set {
            this.pagesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string per_page {
        get {
            return this.per_pageField;
        }
        set {
            this.per_pageField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string total {
        get {
            return this.totalField;
        }
        set {
            this.totalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.worldbank.org")]
public partial class countriesCountry {

    private string iso2CodeField;

    private string nameField;

    private string capitalCityField;

    private string longitudeField;

    private string latitudeField;

    private countriesCountryRegion[] regionField;

    private countriesCountryAdminregion[] adminregionField;

    private countriesCountryIncomeLevel[] incomeLevelField;

    private countriesCountryLendingType[] lendingTypeField;

    private string idField;

    /// <remarks/>
    public string iso2Code {
        get {
            return this.iso2CodeField;
        }
        set {
            this.iso2CodeField = value;
        }
    }

    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }

    /// <remarks/>
    public string capitalCity {
        get {
            return this.capitalCityField;
        }
        set {
            this.capitalCityField = value;
        }
    }

    /// <remarks/>
    public string longitude {
        get {
            return this.longitudeField;
        }
        set {
            this.longitudeField = value;
        }
    }

    /// <remarks/>
    public string latitude {
        get {
            return this.latitudeField;
        }
        set {
            this.latitudeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("region", IsNullable=true)]
    public countriesCountryRegion[] region {
        get {
            return this.regionField;
        }
        set {
            this.regionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("adminregion", IsNullable=true)]
    public countriesCountryAdminregion[] adminregion {
        get {
            return this.adminregionField;
        }
        set {
            this.adminregionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("incomeLevel", IsNullable=true)]
    public countriesCountryIncomeLevel[] incomeLevel {
        get {
            return this.incomeLevelField;
        }
        set {
            this.incomeLevelField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("lendingType", IsNullable=true)]
    public countriesCountryLendingType[] lendingType {
        get {
            return this.lendingTypeField;
        }
        set {
            this.lendingTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.worldbank.org")]
public partial class countriesCountryRegion {

    private string idField;

    private string iso2codeField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string iso2code {
        get {
            return this.iso2codeField;
        }
        set {
            this.iso2codeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.worldbank.org")]
public partial class countriesCountryAdminregion {

    private string idField;

    private string iso2codeField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string iso2code {
        get {
            return this.iso2codeField;
        }
        set {
            this.iso2codeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.worldbank.org")]
public partial class countriesCountryIncomeLevel {

    private string idField;

    private string iso2codeField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string iso2code {
        get {
            return this.iso2codeField;
        }
        set {
            this.iso2codeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.worldbank.org")]
public partial class countriesCountryLendingType {

    private string idField;

    private string iso2codeField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string iso2code {
        get {
            return this.iso2codeField;
        }
        set {
            this.iso2codeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.worldbank.org")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.worldbank.org", IsNullable=false)]
public partial class NewDataSet {

    private countries[] itemsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("countries")]
    public countries[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
